# Generated by Django 5.0.3 on 2024-04-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='320', upload_to='predictedImages/', width_field='320')),
                ('prediction', models.CharField(max_length=254)),
            ],
        ),
    ]
